version: '3.3'

volumes:
  pg_data_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: 
      - .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: antony41991/foodgram_backend
    env_file: 
      - .env
    volumes:
     - static:/static/
     - media:/app/media
    depends_on:
      - db
  frontend:
    image: antony41991/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    env_file: 
      - .env
    image: antony41991/foodgram_nginx
    ports:
      - "7000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend